const EVENT_NAME = {

    REGISTER : 'REGISTER',
    LOGIN:'LOGIN',
    ADD_POST:'ADD_POST',
    LIKE_POST:'LIKE_POST',
    ROOM:'ROOM',
    POST_LIST:'POST_LIST',
    ADD_COMMENT :'ADD_COMMENT',
    COMMENT_LIST:'COMMENT_LIST'

}

module.exports = EVENT_NAME;